using System.Net;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Options;
using modular_mlm.Infrastructure.Email;
using ApplicationEmailSender = modular_mlm.Application.Common.Interfaces.IEmailSender;

namespace modular_mlm.Infrastructure.Identity;

/// <summary>
/// Connects the email operations generated by MapIdentityApi to the application's
/// configured SMTP transport (Resend in production).
/// </summary>
public sealed class IdentityEmailSender(
    ApplicationEmailSender emailSender,
    IOptions<IdentitySecurityOptions> options
) : IEmailSender<ApplicationUser>
{
    private readonly IdentitySecurityOptions _options = options.Value;

    public Task SendConfirmationLinkAsync(
        ApplicationUser user,
        string email,
        string confirmationLink
    ) =>
        emailSender.SendAsync(
            email,
            "Confirm your email address",
            $"""
            Confirm your email address by opening this link:

            {DecodeLink(confirmationLink)}

            If you did not create this account, you can ignore this email.
            """,
            CancellationToken.None
        );

    public Task SendPasswordResetLinkAsync(ApplicationUser user, string email, string resetLink) =>
        emailSender.SendAsync(
            email,
            "Reset your password",
            $"""
            Reset your password by opening this link:

            {DecodeLink(resetLink)}

            If you did not request a password reset, you can ignore this email.
            """,
            CancellationToken.None
        );

    public Task SendPasswordResetCodeAsync(ApplicationUser user, string email, string resetCode)
    {
        var resetLink = BuildPasswordResetLink(email, resetCode);
        return emailSender.SendAsync(
            email,
            "Reset your password",
            $"""
            Reset your password by opening this link:

            {resetLink}

            If you did not request a password reset, you can ignore this email.
            """,
            CancellationToken.None
        );
    }

    private static string DecodeLink(string link) => WebUtility.HtmlDecode(link);

    private string BuildPasswordResetLink(string email, string resetCode)
    {
        var baseUrl = _options.PasswordResetBaseUrl;
        var separator = string.IsNullOrEmpty(baseUrl.Query) ? "?" : "&";
        return $"{baseUrl}{separator}email={Uri.EscapeDataString(email)}&code={Uri.EscapeDataString(resetCode)}";
    }
}
