"use client";

import {
  useApiClient,
  useApiQuery,
  useFormSubmission,
} from "@modular-mlm/api-client";
import {
  Alert,
  Button,
  Card,
  EmptyState,
  PageHeader,
  SelectField,
  ToastRegion,
  useConfirmation,
} from "@modular-mlm/design-system";
import QRCode from "qrcode";
import Image from "next/image";
import { useEffect, useState } from "react";
import { useAgentStorefrontUrl } from "../../app/providers";
import { agentApi } from "../api/agentApi";
import { Failure, Loading } from "../shared/AgentScreenState";
import { useAgentScope } from "../shared/useAgentScope";

export function ReferralToolsPage() {
  const api = useApiClient();
  const { confirm } = useConfirmation();
  const regeneration = useFormSubmission();
  const generation = useFormSubmission();
  const scope = useAgentScope();
  const storefrontUrl = useAgentStorefrontUrl();
  const referral = useApiQuery(
    (client, signal) => agentApi.referral(client, scope.organizationId, signal),
    [scope.organizationId],
    scope.isReady,
  );
  const products = useApiQuery(
    (client, signal) => agentApi.products(client, scope.organizationId, signal),
    [scope.organizationId],
    scope.isReady,
  );
  const dashboard = useApiQuery(
    (client, signal) =>
      agentApi.referralDashboard(
        client,
        scope.organizationId,
        scope.agentId,
        signal,
      ),
    [scope.organizationId, scope.agentId],
    scope.isReady,
  );
  const context = useApiQuery(
    (client, signal) => agentApi.context(client, scope.organizationId, signal),
    [scope.organizationId],
    scope.isReady,
  );
  const [productId, setProductId] = useState("");
  const [productLink, setProductLink] = useState("");
  const [qr, setQr] = useState("");
  const [message, setMessage] = useState("");
  const generalLink = dashboard.data?.storefrontUrl
    ? new URL(dashboard.data.storefrontUrl, storefrontUrl).toString()
    : "";
  useEffect(() => {
    const value = productLink || generalLink;
    if (!value) return;
    void QRCode.toDataURL(value, { width: 240, margin: 1 }).then(setQr);
  }, [generalLink, productLink]);
  if (
    referral.isLoading ||
    products.isLoading ||
    dashboard.isLoading ||
    context.isLoading
  )
    return <Loading />;
  if (referral.error)
    return <Failure error={referral.error} retry={referral.reload} />;
  if (dashboard.error)
    return <Failure error={dashboard.error} retry={dashboard.reload} />;
  if (products.error)
    return <Failure error={products.error} retry={products.reload} />;
  if (context.error)
    return <Failure error={context.error} retry={context.reload} />;
  const copy = async (value: string) => {
    try {
      await navigator.clipboard.writeText(value);
      setMessage("Referral link copied.");
    } catch {
      setMessage("The link could not be copied. Select and copy it manually.");
    }
  };
  return (
    <div className="content-stack">
      <PageHeader
        title="Referral tools"
        description="Links are generated by the backend and preserved exactly."
      />
      {!!regeneration.formErrors.length && (
        <Alert title="Referral code could not be regenerated" tone="danger">
          {regeneration.formErrors.join(" ")}
        </Alert>
      )}
      {!!generation.formErrors.length && (
        <Alert title="Product link could not be generated" tone="danger">
          {generation.formErrors.join(" ")}
        </Alert>
      )}
      {!context.data?.canShareReferralLinks && (
        <Alert title="Referral sharing is unavailable" tone="warning">
          Your Agent account must be active before referral links can be shared.
        </Alert>
      )}
      {dashboard.data && (
        <div className="metric-grid">
          <ReferralMetric
            label="Direct recruits"
            value={String(dashboard.data.directRecruitCount)}
          />
          <ReferralMetric
            label="Attributed orders"
            value={String(dashboard.data.attributedOrderCount)}
          />
          <ReferralMetric
            label="Attributed sales"
            value={new Intl.NumberFormat(undefined, {
              style: "currency",
              currency: scope.currency,
            }).format(dashboard.data.attributedSales)}
          />
          <ReferralMetric
            label="Pending commission"
            value={new Intl.NumberFormat(undefined, {
              style: "currency",
              currency: scope.currency,
            }).format(dashboard.data.pendingCommission)}
          />
          <ReferralMetric
            label="Available commission"
            value={new Intl.NumberFormat(undefined, {
              style: "currency",
              currency: scope.currency,
            }).format(dashboard.data.availableCommission)}
          />
        </div>
      )}
      {!referral.data ? (
        <EmptyState
          title="Referral link unavailable"
          description="Your Agent account cannot share referrals yet."
        />
      ) : (
        <div className="detail-grid">
          <Card>
            <h2>General storefront link</h2>
            <p className="breakable">{generalLink}</p>
            <Button
              disabled={!context.data?.canShareReferralLinks || !generalLink}
              onClick={() => void copy(generalLink)}
            >
              Copy link
            </Button>
            <Button
              variant="danger"
              isLoading={regeneration.isSubmitting}
              disabled={
                regeneration.isSubmitting ||
                !context.data?.canShareReferralLinks
              }
              onClick={async () => {
                if (
                  !(await confirm({
                    title: "Regenerate referral code?",
                    description:
                      "Existing referral links using your current code will stop resolving. Share the new link after regeneration.",
                    confirmLabel: "Regenerate code",
                  }))
                )
                  return;
                const code = await regeneration.submit(
                  () =>
                    agentApi.regenerateReferralCode(
                      api,
                      scope.organizationId,
                      scope.agentId,
                    ),
                  "Referral code regenerated.",
                );
                if (code) {
                  setProductLink("");
                  setMessage(
                    "Referral code regenerated. Copy and share the new link.",
                  );
                  referral.reload();
                  dashboard.reload();
                }
              }}
            >
              Regenerate code
            </Button>
            <h2>Product-specific link</h2>
            <SelectField
              id="referral-product"
              label="Product"
              value={productId}
              onChange={(event) => setProductId(event.target.value)}
            >
              <option value="">Select product</option>
              {products.data?.map((product) => (
                <option key={product.id} value={product.id}>
                  {product.name}
                </option>
              ))}
            </SelectField>
            <Button
              isLoading={generation.isSubmitting}
              disabled={
                !productId ||
                generation.isSubmitting ||
                !context.data?.canShareReferralLinks
              }
              onClick={async () => {
                let canonicalUrl = "";
                const generated = await generation.submit(async () => {
                  const result = await agentApi.productReferral(
                    api,
                    scope.organizationId,
                    productId,
                  );
                  canonicalUrl = result.canonicalUrl;
                }, "Product referral link generated.");
                if (generated) setProductLink(canonicalUrl);
              }}
            >
              Generate product link
            </Button>
            {productLink && (
              <>
                <p className="breakable">{productLink}</p>
                <Button
                  variant="secondary"
                  onClick={() => void copy(productLink)}
                >
                  Copy product link
                </Button>
              </>
            )}
          </Card>
          <Card>
            <h2>QR code</h2>
            {qr ? (
              <Image
                src={qr}
                alt="QR code for the selected referral link"
                width={240}
                height={240}
                unoptimized
              />
            ) : (
              <p>Generate a link to create its QR code.</p>
            )}
            <p>QR content is the canonical link without shortening.</p>
          </Card>
        </div>
      )}
      <ToastRegion>{message && <p>{message}</p>}</ToastRegion>
    </div>
  );
}

function ReferralMetric({ label, value }: { label: string; value: string }) {
  return (
    <Card>
      <span>{label}</span>
      <strong className="metric-value">{value}</strong>
    </Card>
  );
}
