<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>modular_mlm.Shared</RootNamespace>
    <AssemblyName>modular_mlm.Shared</AssemblyName>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
